deviceprofiles:
  - name: qalcosonic
    decoder: qalcosonic
    interval: 3600
    types:
      - urn:oma:lwm2m:ext:3
      - urn:oma:lwm2m:ext:3424
      - urn:oma:lwm2m:ext:3303
  - name: axsensor
    decoder: axsensor
    interval: 3600 
    types:
      - urn:oma:lwm2m:ext:3
      - urn:oma:lwm2m:ext:3330
      - urn:oma:lwm2m:ext:3304
      - urn:oma:lwm2m:ext:3327
      - urn:oma:lwm2m:ext:3303
