version: '3'
services:
  rabbitmq:
    image: 'bitnami/rabbitmq:3.8'
    #image: 'arm64v8/rabbitmq:3.8'
    environment:
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'bitnami'
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672'
      - '15672'
    volumes:
      - 'rabbitmq_data:/bitnami'
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 2s
      timeout: 2s
      retries: 60
      start_period: 20s

volumes:
  rabbitmq_data:
    driver: local
