version: '3'
services:
  postgresqls:
    container_name: "postgres"
    image: "postgres"
    ports:
      - "5433:5432"
    volumes:
       - db_persdata:/var/lib/postgrespers
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: iot-device-mgmt
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@diwise.se
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db_persdata : {}
  pgadmin-data:
